### DISCUSSION TITLE
v1.0.0 - Initial Release 🎉

### DISCUSSION THREAD

**Discussion by Matejkob** [Matejkob/swift-macro-compatibility-check#12] [Announcements]
## Key Features:
- **Version Compatibility Testing**: Automatically checks the compatibility of your Swift package with various `swift-syntax` versions.
  - Supports all versions from `509.0.0` to `600.0.0`.
  - Option to check either all versions or major versions only.
  
- **Test Automation**:
  - Optional flag (`--run-tests`) to run your unit tests after resolving and building each `swift-syntax` version.
  
- **Flexible Configurations**:
  - Flag to run checks against **all versions** or **major versions only** (`--major-versions-only`).
  - Option to enable **verbose mode** (`--verbose`) for detailed output, making it easier to debug issues.

- **Detailed Summary**:
  - The action provides a comprehensive summary of compatibility results, listing both successful and failed versions with clear messaging.

- **Color-Coded Output**:
  - Makes use of color-coded console output to highlight key information, such as successful builds (green), skipped tests (yellow), and failures (red).

## Usage:

To integrate this Action into your workflow, add the following snippet to your GitHub Actions `.yml` file:

```yml
name: Swift Macro Compatibility Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compatibility-check:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Swift Macro Compatibility Check
      run: |
        ./swift-macro-compatibility-check.sh --run-tests --major-versions-only --verbose
```

## Inputs:
- `--run-tests`: Run your Swift package tests after building each `swift-syntax` version.
- `--major-versions-only`: Limit compatibility checks to major versions of `swift-syntax`.
- `--verbose`: Output detailed build and test logs to assist in debugging.

<hr /><em>This discussion was created from the release <a href='https://github.com/Matejkob/swift-macro-compatibility-check/releases/tag/v1.0.0'>v1.0.0 - Initial Release 🎉</a>.</em>
